/*
 * midiFiles.h
 *
 *  Created on: 26.07.2024
 *      Author: stuibeal
 */

#ifndef MIDIFILES_H_
#define MIDIFILES_H_

/*#define M(X) ((const __FLASH char[]) { X })
 static const __FLASH char * const __FLASH miditunes[] = {

 };
 */
const char midifile_1[] PROGMEM = "/midi/130AZZUR.MID";
const char midifile_2[] PROGMEM = "/midi/17 - Zero Hour.mid";
const char midifile_3[] PROGMEM = "/midi/18 - The Ultimate Challenge.mid";
const char midifile_4[] PROGMEM = "/midi/200104.mid";
const char midifile_5[] PROGMEM = "/midi/200105.mid";
const char midifile_6[] PROGMEM = "/midi/200106.mid";
const char midifile_7[] PROGMEM = "/midi/3_13_A_Great_Success.mid";
const char midifile_8[] PROGMEM = "/midi/5min.mid";

const char * const miditunes[] PROGMEM = {
	midifile_1,
	midifile_2,
	midifile_3,
	midifile_4,
	midifile_5,
	midifile_6,
	midifile_7,
	midifile_8
};

/*
 "60'er-Jaren-Medley-04.mid",
 "60'er-Jaren-Medley-07.mid",
 "60'er-Jaren-Medley-09.mid",
 "60'er-Jaren-Medley-13.mid",
 "60'er-Jaren-Medley-14.mid",
 "61401_03.MID",
 "61401_05.MID",
 "682-SCHW.MID",
 "683-SEXY.MID",
 "684_SPEN.MID",
 "689-GANZ.MID",
 "697_ITS_.MID",
 "71001_10.MID",
 "717_KAIS.MID",
 "723SIERR.MID",
 "72641_08.MID",
 "72751_06.MID",
 "72752_07.MID",
 "72752_10.MID",
 "76-02-mouse.mid",
 "7JODELAU.MID",
 "7_mares.mid",
 "80smegamix.mid",
 "82952_06.MID",
 "82952_10.MID",
 "82953_03.MID",
 "82953_09.MID",
 "84000_04.MID",
 "840321a.mid",
 "865GLORI.MID",
 "90203_10.MID",
 "90204_01.MID",
 "90204_07.MID",
 "92057_GM.MID",
 "92501_07.MID",
 "93003_01.MID",
 "93003_05.MID",
 "93003_08.MID",
 "93005_02.MID",
 "93501_04.MID",
 "93501_06.MID",
 "93501_07.MID",
 "94002_06.MID",
 "999_GS2.MID",
 "99redbaloons_nena.mid",
 "ac_dc-thunderstruck.mid",
 "Advert-CocaCola_Comercial.mid",
 "AFROCUBA.MID",
 "AIR.MID",
 "ALF.mid",
 "AllyMcbeal.Mid",
 "Babar.mid",
 "BANDIT.MID",
 "bavarian.mid",
 "Bayrischer-Landler.mid",
 "Bayrischzell.mid",
 "Beinhart-1.mid",
 "Beinhart-2.mid",
 "Benny_Hill.mid",
 "BlackAdderTheme.mid",
 "CagneyAndLacey.mid",
 "CHATCHOO.MID",
 "Chron.mid",
 "Dallas.mid",
 "DangerMouse.mid",
 "d_e1m1.mid",
 "d_inter.mid",
 "DM2TTL.MID",
 "Dogtanian.mid",
 "Dott.mid",
 "DrSnuggles.mid",
 "d_runni2.mid",
 "E2M3.MID",
 "Egerlander-Musikantenmarsch.mid",
 "Egerland-Heimatland-2.mid",
 "Eine-Neue-Liebe-Ist-Wie-Ein-Neues-Leben-2.mid",
 "Eine-Weisse-Rose-2.mid",
 "Ein-Prosit-1.mid",
 "Ein-Prosit-2.mid",
 "Ein-Prosit-3.mid",
 "EleanorRigby3.mid",
 "ELISE.MID",
 "EMDALLAS.mid",
 "EMF.MID",
 "eminem-just_lose_it.mid",
 "eminem-mockingbird.mid",
 "EMINEM.My name is.mid",
 "eminem-space_bound_piano_version.mid",
 "EMINEM.The real slim shady.mid",
 "EMINEM.The way i am.mid",
 "eminem-without_me.mid",
 "Endtitle.mid",
 "Eric_Clapton_-_Layla.mid",
 "FALLGUY.mid",
 "FERNANDO.MID",
 "FIRERAIN.MID",
 "FUGUEGM.MID",
 "GANGNAM.MID",
 "GBROWN.MID",
 "GDVIB6.MID",
 "german3.mid",
 "GilligansIsland.mid",
 "Gloria 1999(k).mid",
 "grabbag.mid",
 "Greent.mid",
 "GummiBears.mid",
 "HartToHart.mid",
 "Heidewitzka-Herr-Kapitan.mid",
 "heilprosit.mid",
 "heretic.mid",
 "Highway.mid",
 "House.mid",
 "I-Bin-A-Bayrischer-Cowgirl-1.mid",
 "IGGY POP.Lust for life.mid",
 "INDY3END.MID",
 "indy4Theme and Opening Credits.mid",
 "Inpast.mid",
 "Io_vagabondo.mid",
 "IPANEMA.mid",
 "james_bo.mid",
 "JAZZ.MID",
 "JZBUMBLE.MID",
 "Kate Ryan - Libertine.mid",
 "KATZEKLO.MID",
 "keen.mid",
 "kraftwerk-radioactivity.mid",
 "leaving_schlosskeller_bummbuumm.MID",
 "LittleBritain.mid",
 "LOOPDEMO.MID",
 "m1theme-dg.mid",
 "m2intro.mid",
 "Macgyver.mid",
 "Magnum.mid",
 "MAP01.MID",
 "Map.mid",
 "Matlock.mid",
 "meravigl(1).mid",
 "Meravigliosa creatura.mid",
 "mi2-vorspann-dg.mid",
 "MiamiVice.mid",
 "MINUET.MID",
 "MonkTVTheme.mid",
 "MontyPython_LifeOfBrian.mid",
 "MOZART.MID",
 "Munsters_3.mid",
 "NASOWAS.MID",
 "National Anthem - Czech Republic.mid",
 "National Anthem - Germany.mid",
 "National Anthem - Luxembourg.mid",
 "National Anthem - New Zealand.mid",
 "National_Anthems_-_Italy.mid",
 "National_Anthems_-_Switzerland.mid",
 "National_Anthems_-_United_States.mid",
 "Nirvana_-_Lithium.mid",
 "NIRVANA.Smells like teen spirit K.mid",
 "Nur-Ein-Tanz-Und-Dann-A-Basserl.mid",
 "Ode-To-Joy.mid",
 "ODETOJOY.MID",
 "Pingu.mid",
 "POPCORN.MID",
 "PRDANCER.MID",
 "PROWLER.MID",
 "RemingtonSteele.mid",
 "Seinfeld.mid",
 "siemens-S6.mid",
 "SKYFALL.MID",
 "SONATAC.MID",
 "startme.mid",
 "STRIPPER.MID",
 "SYMPH9.MID",
 "Tdisco.mid",
 "Thank You For The Music.mid",
 "Titanic - Rose.mid",
 "TWINKLE.MID",
 "TWINPEA.MID",
 "Uber-Den-Wolken-1.mid",
 "Wagner Ride of the valkyries.mid",
 "What-Time-Is-Love.mid",
 "X-Files_Extended.mid",
 "XMAS.MID",
 "Zorba.mid",
 "zorbas2.mid"

 };
 */

#endif /* MIDIFILES_H_ */
